<?php
const NO_SUCH_API_KEY = 14;

const ARG_EMAIL_INVALID = 3;
const ARG_PASSWORD_EMPTY = 4;
const ARG_USERNAME_EMPTY = 5;
const ARG_LOG_TYPE_EMPTY = 6;
const ARG_LOG_VALUE_EMPTY = 7;

const LOGIN_FAILED = 15;

?>
